[package]
name = "macos-unifiedlogs"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
serde_json = "1.0.114"
serde = { version = "1.0.197", features = ["derive"] }
log = "0.4.21"
lz4_flex = "0.11.2"
byteorder = "1.5.0"
plist = "1.6.0"
regex = "1.10.3"
base64 = "0.22.0"
chrono = "0.4.34"

[dev-dependencies]
simplelog = "0.12.1"
csv = "1.3.0"
chrono = "0.4.34"
criterion = "0.5.1"

[[bench]]
name = "high_sierra_benchmark"
harness = false

[[bench]]
name = "big_sur_benchmark"
harness = false

[[bench]]
name = "monterey_benchmark"
harness = false
